attacks:


  fgsm:

    epsilons:

      - 0.03137

      - 0.2



  pgd:

    epsilons:

      - 0.03137

      - 0.2


    steps:

      - 10



  text:


    synonym:

      ratios:

        - 0.2

        - 0.4


    deletion:

      ratio: 0.5
